#Multi-VAE config.yaml
seed: 1111
data: "/opt/ml/input/data/train/"
lr: 1.0e-4
wd: 0.00
batch_size: 500
epochs: 200
total_anneal_steps: 200000
anneal_cap: 0.2
cuda: True
log_interval: 100
patience: 10
checkpoint_path: "Multi_VAE.pth"
name : "experiment" # 실험 명칭